### ISSUE TITLE
Prompt = False gets ignored

### ISSUE THREAD

**Issue by mikkelkrogsholm** [quanteda/spacyr#102]
Hi. Its seems that you are not able to get around the prompts using `prompt = FALSE` because the `spacy_install()` function takes doesn't use it when looking for conda and there for prompts. See below:

`            # validate that we have conda
            if (!have_conda) {
                cat("No conda was found in the system. ")
                ans <- utils::menu(c("No", "Yes"), title = "Do you want spacyr to download miniconda in ~/miniconda?")
                if (ans == 2) {
                  install_miniconda()
                  conda <- tryCatch(reticulate::conda_binary('auto'), error = function(e) NULL)
                } else stop("Conda environment installation failed (no conda binary found)\n", call. = FALSE)
            }`

I am happy to do a pull request to fix it if you want?

**Comment by kbenoit** [comment]
Thanks! Please do fix it and issue a PR.

**Comment by amatsuo** [comment]
No @kbenoit. Please wait for my comment.

**Comment by kbenoit** [comment]
I stand corrected! 😨

**Comment by amatsuo** [comment]
Hello,

Thanks for the feedback. That's an intended behavior. The `prompt  = FALSE` option is created mostly for automating installation for travis-build. Since we know that conda already exists when `spacy_install()` is invoked in `.travis.yml`, we do not have to give spacyr a permission to skip the prompt to install `miniconda`.

We (or at least I) are not comfortable with installing a software without an explicit approval from a user even when `prompt = FALSE` is chosen. 

That's the reason why the option is set up like this. What do you think @kbenoit?

**Comment by mikkelkrogsholm** [comment]
Ok. I see.

I run into the issue because I am installing it via a docker file and not
interactively so my build fails because I can't answer the prompt.

**Comment by amatsuo** [comment]
The installation command of miniconda from `spacy_install()` does basically the same as the following lines in `.travis.yml`. 

https://github.com/quanteda/spacyr/blob/master/.travis.yml#L32-L36

You can sneak something like this in your deployment.
