### ISSUE TITLE
Solution then

### ISSUE THREAD

**Issue by JoeTorino** [quanteda/spacyr#123]
Is there a way then to fix this issue?
I installed the spacy library as you suggested by using **conda install -c conda-forge spacy** 
and it worked. Unfortunately I still automatically create a link when I download NLP languages._

**Comment by amatsuo** [comment]
Hello,

I am not sure what exactly is the issue. Could you elaborate a bit more? 

In particular, what do you mean by
>  I still automatically create a link when I download NLP languages.

**Comment by JoeTorino** [comment]
Hi,

Sorry I have resolved the issue, when I downloaded the nlp languages I wanted spacy to work with the automatic link that registers when you download the languages was not created.


e.g.


"python -m spacy download en          Result: “Download successful but linking failed”
python -m spacy download it          Result: “Download successful but linking failed”

Creating a shortcut link for 'en' didn't work (maybe you don't have
    admin permissions?), but you can still load the model via its full
    package name: nlp = spacy.load('{name}')
"


I ran the command prompt as an administrator and the link between spacy and the downloaded language "library/directory" was created in the end. Now everything seems to be working.

________________________________
Da: Aki Matsuo <notifications@github.com>
Inviato: martedì 3 luglio 2018 13:47
A: quanteda/spacyr
Cc: JoeTorino; Author
Oggetto: Re: [quanteda/spacyr] Solution then (#123)


Hello,

I am not sure what exactly is the issue. Could you elaborate a bit more?

In particular, what do you mean by

I still automatically create a link when I download NLP languages.

**Comment by amatsuo** [comment]
It is a bit confusing situation. Linking failure usually happens when your account does not have a sufficient privilege. What spaCy does when installing the model with an abbreviated name is first to download a model, then create a symlink to it. If you cannot write in the folder where the symlink will be placed, the error you saw occurs.

I believe you can still initialize spacy with the model's long name. For example, to load the standard English model, you can enter:
```r
spacy_initialize("en_core_web_sm")
```
See: https://spacy.io/usage/models

Another possible solution is to use conda environment using `spacy_install` where you don't need an admin privilege (but it's not available for Windows...).
