### ISSUE TITLE
compatibility with spacy 2.1?

### ISSUE THREAD

**Issue by randomgambit** [quanteda/spacyr#161]
Hello there, I just installed `spacy 2.1` and I was not able to make `spacyr` run anymore.

The usual command I used to ran is
```

spacy_initialize(model = '//mydata/en_core_web_lg-2.1.0/en_core_web_lg/en_core_web_lg-2.1.0',
                 python_executable = 'C:\\Users\\john\\AppData\\Local\\Continuum\\anaconda3\\python.exe')
```

which now returns   

> C:\Users\john\AppData\Local\Continuum\anaconda3\python.exe is not a python executable

Is this a `spacyr` bug? This code literally worked fine yesterday before the spacy update via conda.

Thanks!

**Comment by kbenoit** [comment]
See https://twitter.com/amatsuo_net/status/1107718241022033920

**Comment by amatsuo** [comment]
The error seems not related to the spacy version. 

My hunch is that the issue is caused by a missing path to python. In the command prompt, could you try `where python` and check whether your python (i.e. `C:\Users\john\AppData\Local\Continuum\anaconda3\python.exe`) comes up? (For more info, see [here](https://stackoverflow.com/questions/34030373/anaconda-path-environment-variable-in-windows)). 

If not, try setting it. Probably, [this](https://superuser.com/questions/143119/how-do-i-add-python-to-the-windows-path) will work.

Or alternatively, try `spacy_install()` which will create a conda environment for spacy. Please remember this will take up several hundreds megabytes of your disk space, but this is our recommendation for using spaCy in R.

**Comment by randomgambit** [comment]
thanks @amatsuo. running `where python` in the conda console returns the same path for the python executable. 

As I told you, this exact set up worked with Spacy 2. so this is why I was thinking this was related to 2.1.
Do you have other ideas? Can I use `spacy_install` with a custom model loaded from a path?

**Comment by amatsuo** [comment]
That's weird. The error message is coming from checking the python executable through `where python` (https://github.com/quanteda/spacyr/blob/master/R/spacy_initialize.R#L206-L218). 

You can try `py_exec %in% system2("where", "python", stdout = TRUE)` (or something similar) and see what returns. Maybe double backslashes and forward slashes differences?

Anyway, the `spacy_install()` method should be fine too, as long as your custom model is compatible with spaCy 2.1.

**Comment by randomgambit** [comment]
@amatsuo running your command returns an error

> py_exec %in% system2("where", "python", stdout = TRUE)
Error in py_exec %in% system2("where", "python", stdout = TRUE) : 
  object 'py_exec' not found

however, running `> reticulate::py_config()` will return the correct python path in `python versions found` (2 other versions are found somewhere else)

the problem with `spacy_install()` is that it needs internet connectivity which does not work with my corporate firewall... and I need to load my custom model from a path too (cant have admin rights for the simulink stuff).

Again, what is puzzling is that everything worked just fine before updating to `2.1`.
Thanks!

**Comment by amatsuo** [comment]
you need to assigning value to `py_exec`.... (e.g. `py_exec <- 'C:\\Users\\john\\AppData\\Local\\Continuum\\anaconda3\\python.exe'`)

**Comment by randomgambit** [comment]
ha! that solves part of the issue! (but makes me wonder why the `python_executable` argument does not work then) 

now the error changed into:
```

Error in spacy_initialize(python_executable = "C:\\Users\\john\\AppData\\Local\\Continuum\\anaconda3\\python.exe",  : 
  spaCy or language model \\mydata\en_core_web_lg-2.1.0\en_core_web_lg\en_core_web_lg-2.1.0 is not installed in C:\Users\john\AppData\Local\Continuum\anaconda3\python.exe
```

However, using `nlp = spacy.load('\\mydata\en_core_web_lg-2.1.0\en_core_web_lg\en_core_web_lg-2.1.0')` works perfectly fine in `anaconda`... 

are you able to load a downloaded model from path (the way I do it) with spacy 2.1 on your system?  What do you think? Thanks again!

**Comment by amatsuo** [comment]
I am not sure (as my knowledge on windows is limited...), but I suspect the interpretation of double slashes might be a problem. Could you try using full path from the drive letter?

**Comment by randomgambit** [comment]
I was able to make it work with

1. loading `reticulate` first and using 

```
py_run_string("import spacy")
py_run_string("nlp = spacy.load('/////mydata/en_core_web_lg-2.1.0/en_core_web_lg/en_core_web_lg-2.1.0')")
```

2. then loading `spacyr` and using `spacy_initialize` with the full model path.

Strange isnt it?
Thanks!

**Comment by lhami** [comment]
It looks like there's still an issue with the way that spacyr is checking the Windows PATH, maybe doing a literal string comparison instead of interpreting the passed-in python_executable and/or PATH as file positions?

Using R 4.3.0, reticulate 1.2.8, and spacyr 1.7.12, the following fails:
```
> spacy_initialize(python_executable = "C:/Program Files/WinPy/WPy64-39100/python-3.9.10.amd64/python.exe")
Error in check_spacy_model(python_executable, model) : 
  C:/Program Files/WinPy/WPy64-39100/python-3.9.10.amd64/python.exe is not a python executable
```

Which is a filepath that would be recognized by most packages in R, but when I swap out for double backslashes it runs successfully:

```
> spacy_initialize(python_executable = "C:\\Program Files\\WinPy\\WPy64-39100\\python-3.9.10.amd64\\python.exe")
successfully initialized (spaCy Version: 3.5.2, language model: en_core_web_sm)
(python options: type = "python_executable", value = "C:\Program Files\WinPy\WPy64-39100\python-3.9.10.amd64\python.exe")
```

This is a little annoying since using the RStudio autocomplete to generate the file path puts single forward slashes instead of double backslashes. And `find_spacy()` doesn't successfully find my WinPython install, which is fair, but I imagine Windows users will continue to run up against this problem.

Is there a reason it's checking the PATH to figure out if python.exe is a python executable?
