### ISSUE TITLE
Error in path.expand(path) : invalid 'path' argumen when trying spacy_initialize

### ISSUE THREAD

**Issue by beltranster** [quanteda/spacyr#179]
Hi, I am trying to use spacyr and I dont have admin privileges to my machine.  
I am running:
install.packages("spacyr")
library(spacyr)
without any error messages

however, when  I try to run spacy_initialize, I get the error: 
Error in path.expand(path) : invalid 'path' argument

I have tried different options for the arguments of the function with no success. Any advice? 
Thanks

**Comment by kbenoit** [comment]
Should be solved now in current `master`.

**Comment by erichround** [comment]
Hi, I'm using R v3.6.2 through rstudio v1.2.5033 on Mac OS 10.15.7.  I have this same problem.  I've tried installing both python 3.8 (which is the current miniconda default) and also 3.6.10, and it makes no difference.  

I've tried specifying a path using the conda parameter. This either returns a the same error "Error in path.expand(path) : invalid 'path' argument" or it reports installing conda and then gives the same path error:

> spacy_install(conda = "~/Applications/miniconda3/")
No conda was found in the system. Do you want spacyr to download miniconda in ~/miniconda? 

1: No
2: Yes

Selection: 2
Downloading installation script
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0     0    0     0    0     0      0      0 --:--:--  0:00:16 --:--:--     0
Running installation script
Installation of miniconda complete
Error in path.expand(path) : invalid 'path' argument

Any advice on this? Thanks.

**Comment by kbenoit** [comment]
@erichround Have you tried this with the current version of R? (4.0.3)

**Comment by erichround** [comment]
@kbenoit I've tried a few things which I'll tell you about in case any/all are useful. 
- Currently, if I use the Mac installer package to install miniconda, it won't allow me to directly choose my home folder as the install destination. I suspected the path.expand() error was due to spacy_install() looking under the home directory. So, I directed miniconda to install on my HD, but then manually chose my home folder as the directory to use. That solved the spacy_install() path.expand error. However, running spacy_install() then produced an error that my home directory was “Not a conda environment”. So I specified envname = "myenv", and spacy_install() worked. However, spacy_initialize() gives me the #181 problem.
- On another machine, I have R4.0.3 installed, but under an older OS (OS10.12.6). With it, I got the same expand.path error initially. I used the same install workaround for miniconda, and that solved the expand.path problem. Moreover, this time there was no “Not a conda environment” problem, rather, once I'd installed miniconda in my home directory, spacy_install() worked without specifying envname, and spacy_initialize() also worked. This makes it seem like there's some kind of problem with the later OS.
- I haven't yet tried R4.0.3 on the newer OS, for the usual reasons of delaying upgrading while you're in the middle of other things.

Here's my session info from the problematic machine (R3.6.2, OS10.15.7) after running spacy_install()

R version 3.6.2 (2019-12-12)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.7

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] spacyr_1.2.1

loaded via a namespace (and not attached):
[1] compiler_3.6.2    Matrix_1.2-18     tools_3.6.2       Rcpp_1.0.5        reticulate_1.18   grid_3.6.2       
[7] data.table_1.13.2 jsonlite_1.7.1    lattice_0.20-40


Here's my session info from the unproblematic machine (R4.0.3 OS10.12.6) after running spacy_install() and spacy_initialize():

R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Sierra 10.12.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_AU.UTF-8/en_AU.UTF-8/en_AU.UTF-8/C/en_AU.UTF-8/en_AU.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] spacyr_1.2.1

loaded via a namespace (and not attached):
 [1] compiler_4.0.3    Matrix_1.2-18     tools_4.0.3       yaml_2.2.1        reticulate_1.18   Rcpp_1.0.5        grid_4.0.3       
 [8] data.table_1.13.2 jsonlite_1.7.1    lattice_0.20-41

**Comment by omstuhler** [comment]
I held a small workshop this week and multiple people ran into this issue and couldn't install conda from within R. The error message occurs when running ```spacy_initialize()``` after entering "Yes" on the "Do you want to download miniconda in ~/miniconda?" dialogue. It reads as follows:

```
Running installation script
Installation of miniconda complete
Error in path.expand(path): invalid 'path' argument
```

My sense is that the problem seemed to occur with people who (a) were using macs and (b) didn't have Python installed.

I know the following specifications for two participants:

macOS Monterrey 12.0.1, 
platform: x86_64-apple-darwin17.0
R version 4.1.2 (2021-11-01)
RStudio 2021.09.1 Build 372

AND

macOs Big Sur 11.6.1 (20G224)
platform: x86_64-apple-darwin15.6.0
R version 3.6.3 (2020-02-29)
RStudio 2021.09.1 Build 372
